summary: "Add 2 Numbers"
description: "This is a simple API which returns the sum of 2 numbers"
consumes:
- "application/json"
produces:
- "application/json"
parameters:
- in: "body"
  name: "body"
  description: "Accepts a input dictionary of inputs x1 and x2"
  required: true
  schema:
    type: "string"
    example : "aaaa"
responses:
  405:
    description: "Invalid input"