//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.8-b130911.1802 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2022.05.09 at 03:53:13 PM EEST 
//


package ro.anre.anreschema.standard;

import javax.xml.bind.annotation.adapters.XmlAdapter;
import java.time.LocalDate;

public class Adapter2
    extends XmlAdapter<String, LocalDate>
{


    public LocalDate unmarshal(String value) {
        return (ro.anre.anreschema.jaxb.Adapter.parseDate(value));
    }

    public String marshal(LocalDate value) {
        return (ro.anre.anreschema.jaxb.Adapter.printDate(value));
    }

}
